<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('pages', ['as'=> 'pages.index', 'uses' => 'PageController@index']);
Route::post('pages', ['as'=> 'pages.store', 'uses' => 'PageController@store']);
Route::get('pages/create', ['as'=> 'pages.create', 'uses' => 'PageController@create']);
Route::put('pages/{pages}', ['as'=> 'pages.update', 'uses' => 'PageController@update']);
Route::patch('pages/{pages}', ['as'=> 'pages.update', 'uses' => 'PageController@update']);
Route::get('pages/{id}/delete', array('as' => 'pages.delete', 'uses' => 'PageController@getDelete'));
Route::get('pages/{id}/confirm-delete', array('as' => 'pages.confirm-delete', 'uses' => 'PageController@getModalDelete'));
Route::get('pages/{pages}', ['as'=> 'pages.show', 'uses' => 'PageController@show']);
Route::get('pages/{pages}/edit', ['as'=> 'pages.edit', 'uses' => 'PageController@edit']);

Route::get('pages/{pages}/infobox', ['as'=> 'pages.infobox', 'uses' => 'PageController@infobox']);

Route::post('box-category', ['as'=> 'pages.storecategory', 'uses' => 'PageController@storecategory']);
Route::get('pages/{id}/deletecategory', array('as' => 'pages.deletecategory', 'uses' => 'PageController@getCategoryDelete'));
Route::get('get-category/{slug}', array('as' => 'pages.getcategory', 'uses' => 'PageController@getCategory'));
Route::patch('box-category-update', ['as'=> 'pages.updatecategory', 'uses' => 'PageController@updatecategory']);
Route::patch('propertyreport-price-update', ['as'=> 'pages.updateReportPrice', 'uses' => 'PageController@updateReportPrice']);

});



Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('footers', ['as'=> 'footers.index', 'uses' => 'FooterController@index']);
// Route::post('footers', ['as'=> 'footers.store', 'uses' => 'FooterController@store']);
// Route::get('footers/create', ['as'=> 'footers.create', 'uses' => 'FooterController@create']);
Route::put('footers/{footers}', ['as'=> 'footers.update', 'uses' => 'FooterController@update']);
Route::patch('footers/{footers}', ['as'=> 'footers.update', 'uses' => 'FooterController@update']);
// Route::get('footers/{id}/delete', array('as' => 'footers.delete', 'uses' => 'FooterController@getDelete'));
// Route::get('footers/{id}/confirm-delete', array('as' => 'footers.confirm-delete', 'uses' => 'FooterController@getModalDelete'));
Route::get('footers/{footers}', ['as'=> 'footers.show', 'uses' => 'FooterController@show']);
Route::get('footers/{footers}/edit', ['as'=> 'footers.edit', 'uses' => 'FooterController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('webbanners', ['as'=> 'banners.index', 'uses' => 'BannerController@index']);
Route::post('webbanners', ['as'=> 'banners.store', 'uses' => 'BannerController@store']);
Route::get('webbanners/create', ['as'=> 'banners.create', 'uses' => 'BannerController@create']);
Route::put('webbanners/{banners}', ['as'=> 'banners.update', 'uses' => 'BannerController@update']);
Route::patch('webbanners/{banners}', ['as'=> 'banners.update', 'uses' => 'BannerController@update']);
Route::get('webbanners/{id}/delete', array('as' => 'banners.delete', 'uses' => 'BannerController@getDelete'));
Route::get('webbanners/{id}/confirm-delete', array('as' => 'banners.confirm-delete', 'uses' => 'BannerController@getModalDelete'));
Route::get('webbanners/{banners}', ['as'=> 'banners.show', 'uses' => 'BannerController@show']);
Route::get('webbanners/{banners}/edit', ['as'=> 'banners.edit', 'uses' => 'BannerController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('media', ['as'=> 'media.index', 'uses' => 'MediaController@index']);
Route::post('media', ['as'=> 'media.store', 'uses' => 'MediaController@store']);
Route::get('media/create', ['as'=> 'media.create', 'uses' => 'MediaController@create']);
Route::put('media/{media}', ['as'=> 'media.update', 'uses' => 'MediaController@update']);
Route::patch('media/{media}', ['as'=> 'media.update', 'uses' => 'MediaController@update']);
Route::get('media/{id}/delete', array('as' => 'media.delete', 'uses' => 'MediaController@getDelete'));
Route::get('media/{id}/confirm-delete', array('as' => 'media.confirm-delete', 'uses' => 'MediaController@getModalDelete'));
Route::get('media/{media}', ['as'=> 'media.show', 'uses' => 'MediaController@show']);
Route::get('media/{media}/edit', ['as'=> 'media.edit', 'uses' => 'MediaController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {
    
    Route::get('menu-data', 'MenuBuilderController@index')->name('menus.data');
    Route::get('menubuilders', ['as'=> 'menubuilders.index', 'uses' => 'MenuBuilderController@index']);
    Route::post('menubuilders', ['as'=> 'menubuilders.store', 'uses' => 'MenuBuilderController@store']);
    Route::get('menubuilders/create', ['as'=> 'menubuilders.create', 'uses' => 'MenuBuilderController@create']);
    Route::put('menubuilders/{menubuilders}', ['as'=> 'menubuilders.update', 'uses' => 'MenuBuilderController@update']);
    Route::patch('menubuilders/{menubuilders}', ['as'=> 'menubuilders.update', 'uses' => 'MenuBuilderController@update']);
    Route::get('menubuilders/{id}/delete', array('as' => 'menubuilders.delete', 'uses' => 'MenuBuilderController@getDelete'));
    Route::get('menubuilders/{id}/confirm-delete', array('as' => 'menubuilders.confirm-delete', 'uses' => 'MenuBuilderController@getModalDelete'));
    Route::get('menubuilders/{menubuilders}', ['as'=> 'menubuilders.show', 'uses' => 'MenuBuilderController@show']);
    Route::get('menubuilders/{menubuilders}/edit', ['as'=> 'menubuilders.edit', 'uses' => 'MenuBuilderController@edit']);


    Route::get('menubuilders/{builders}/builder', ['as'=> 'menubuilders.builder', 'uses' => 'MenuBuilderController@builder']);

    Route::post('menubuilders/{id}/item', ['as'=> 'builders.store', 'uses' => 'MenuBuilderController@builderStore']);
    Route::post('menubuilders/{id}/order', ['as'=> 'builders.order', 'uses' => 'MenuBuilderController@builderOrder']);

    Route::get('builders/{id}/delete', array('as' => 'builders.delete', 'uses' => 'MenuBuilderController@getBuilderDelete'));
    Route::get('builders/{id}/confirm-delete', array('as' => 'builders.confirm-delete', 'uses' => 'MenuBuilderController@getBuilderModalDelete'));
    Route::get('builders/{id}/edit', ['as'=> 'builders.edit', 'uses' => 'MenuBuilderController@editBuilder']);

});

Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('contactforms', ['as'=> 'contactforms.index', 'uses' => 'ContactformController@index']);
Route::post('contactforms', ['as'=> 'contactforms.store', 'uses' => 'ContactformController@store']);
Route::get('contactforms/create', ['as'=> 'contactforms.create', 'uses' => 'ContactformController@create']);
Route::put('contactforms/{contactforms}', ['as'=> 'contactforms.update', 'uses' => 'ContactformController@update']);
Route::patch('contactforms/{contactforms}', ['as'=> 'contactforms.update', 'uses' => 'ContactformController@update']);
Route::get('contactforms/{id}/delete', array('as' => 'contactforms.delete', 'uses' => 'ContactformController@getDelete'));
Route::get('contactforms/{id}/confirm-delete', array('as' => 'contactforms.confirm-delete', 'uses' => 'ContactformController@getModalDelete'));
Route::get('contactforms/{contactforms}', ['as'=> 'contactforms.show', 'uses' => 'ContactformController@show']);
Route::get('contactforms/{contactforms}/edit', ['as'=> 'contactforms.edit', 'uses' => 'ContactformController@edit']);

});
